// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2830.PeligrosoRobot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Victor;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController drivetrainSpeedController1;
    public static SpeedController drivetrainSpeedController2;
    public static SpeedController drivetrainSpeedController3;
    public static SpeedController drivetrainSpeedController4;
    public static RobotDrive drivetrainRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainSpeedController1 = new Victor(0);
        LiveWindow.addActuator("Drivetrain", "Speed Controller 1", (Victor) drivetrainSpeedController1);
        
        drivetrainSpeedController2 = new Victor(1);
        LiveWindow.addActuator("Drivetrain", "Speed Controller 2", (Victor) drivetrainSpeedController2);
        
        drivetrainSpeedController3 = new Victor(2);
        LiveWindow.addActuator("Drivetrain", "Speed Controller 3", (Victor) drivetrainSpeedController3);
        
        drivetrainSpeedController4 = new Victor(3);
        LiveWindow.addActuator("Drivetrain", "Speed Controller 4", (Victor) drivetrainSpeedController4);
        
        drivetrainRobotDrive41 = new RobotDrive(drivetrainSpeedController1, drivetrainSpeedController2,
              drivetrainSpeedController3, drivetrainSpeedController4);
        
        drivetrainRobotDrive41.setSafetyEnabled(true);
        drivetrainRobotDrive41.setExpiration(0.1);
        drivetrainRobotDrive41.setSensitivity(0.5);
        drivetrainRobotDrive41.setMaxOutput(1.0);


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
